### PR TITLE
Remove BBStmt in AST.lean

### PR DESCRIPTION
**Pull request by math-fehr**
Here is the progress on removing basic block statements from the AST.
I just changed the AST.lean file, tell me if you think this makes sense or not, so I can continue changing this elsewhere.

### CODE REVIEW

**Comment by lephe** [comment]
Rebased on `master`.

**Comment by lephe** [comment]
I updated `EDSL.lean` to get rid of basic block statements. With this Mathieu you should be able to keep going for a while.

**Comment by lephe** [comment]
That's one way to finish it aha

**Comment by math-fehr** [comment]
Siddharth told me to remove those files ;) Though yes, the commit name is quite... yeah

**Pull request merged**
